### ISSUE TITLE
Add "Finish alignment" button to alignment tab

### ISSUE THREAD

**Issue by kimspindel** [SpatialTranscriptomicsResearch/st_spot_detector#46]

**Comment by ludvb** [comment]
The alignment tab has been redesigned since this issue was written and I think a "Finish alignment" button would be inappropriate in the current design. Moreover, the alignment tab can be used to apply image adjustments in order to make certain spots more visible for the spot adjustments. Users may like to go back and forth between the alignment tab and the spot adjustment tab during this process. Therefore, I don't think imposing a sequential workflow, as indicated by the button text, is appropriate in this context. Wontfix.
